In [1]:
1+1

2

In [2]:
1+1.0

2.0

In [3]:
1/2

0.5

In [4]:
1//2

0

In [5]:
1/2.0

0.5

In [6]:
2**4

16

In [7]:
20%3

2

In [8]:
20%3.0

2.0

In [3]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [8]:
x = 'Giri'
y =  23
print('My name is {} and age is {}'.format(x,y))
print('My name is {one} and age is {two}'.format(two=y,one=x))

My name is Giri and age is 23
My name is Giri and age is 23


In [9]:
s = 'Hello'

In [10]:
s[0]

'H'

In [11]:
s[:-1]

'Hell'

In [12]:
s[-1]

'o'

In [27]:
s = 'Giridhar'

In [28]:
print(s[0:4:2])

Giri


In [25]:
for i in range(len(s)):
    print(i, s[i])

0 G
1 i
2 r
3 i
4 d
5 h
6 a
7 r


In [29]:
s[::-1]

'rahdiriG'

In [30]:
a = [1,2,[3,4]]

In [31]:
a[2[1]]

TypeError: 'int' object is not subscriptable

In [32]:
a[2]

[3, 4]

In [33]:
a[2][1]

4

In [34]:
d = {'a':'America', 'b':'Brazil'}

In [37]:
d['b']

'Brazil'

In [42]:
d.keys()

dict_keys(['a', 'b'])

In [43]:
d.values()

dict_values(['America', 'Brazil'])

In [44]:
list_a = [1,2,3]

In [46]:
list_a[0] = 'First'

In [47]:
list_a

['First', 2, 3]

In [48]:
tuple_a = (1,2,3)

In [49]:
tuple_a[0]

1

In [50]:
tuple_a[0] = 'a'

TypeError: 'tuple' object does not support item assignment

In [54]:
seq = [1,2,3,4]

def squarer(ele):
    return(ele**2)
    
list(map(squarer, seq))

[1, 4, 9, 16]

In [55]:
# lambda
list(map(lambda x:x**2, seq))

[1, 4, 9, 16]

In [57]:
import math
list(filter(lambda x:math.sqrt(x), seq))

[1, 2, 3, 4]

In [58]:
a = []
b = a
b.append(1)
a

[1]

In [60]:
from copy import deepcopy
a = []
b = deepcopy(a)
b.append(1)
print(a)

[]


In [61]:
import numpy as np

In [97]:
# series 1
ser1 = []
for i in range(23000):
    ser1.append(np.random.randint(1,100))

In [98]:
len(ser1)

23000

In [99]:
# series 2
ser2 = []
for i in range(23000):
    ser2.append(np.random.randint(1,100))

In [100]:
len(ser2)

23000

In [101]:
import pandas as pd

In [102]:
ser1 = pd.Series(ser1)

In [103]:
ser2 = pd.Series(ser2)

In [104]:
data = pd.concat([ser1, ser2], axis=1)

In [105]:
data

0   1
0      86  94
1      63  80
2      69  32
3      95  56
4      38  47
...    ..  ..
22995  24  65
22996  11  88
22997  94  84
22998  61  19
22999  10  79

[23000 rows x 2 columns]

In [108]:
data[data[0] == data[1]]

0   1
5      92  92
38      9   9
45     42  42
86     45  45
119    22  22
...    ..  ..
22405  14  14
22557  32  32
22858  66  66
22896  49  49
22943  17  17

[229 rows x 2 columns]

In [109]:
exam1 = {'Name':['Giridhar','Phani','Sai'],'Marks_Science':[95,90,93],'Marks_Maths':[99,100,95]}
exam2 = {'Name':['Sai','Giridhar','Phani','Aditya'],'Marks_Maths':[96,100,99,100],'Marks_Science':[94,95,95,100],'Marks_Hindi':[90,95,97,100]}

In [110]:
df_exam1 = pd.DataFrame(exam1)

In [111]:
df_exam1

Name  Marks_Science  Marks_Maths
0  Giridhar             95           99
1     Phani             90          100
2       Sai             93           95

In [112]:
df_exam2 = pd.DataFrame(exam2)

In [113]:
df_exam2

Name  Marks_Maths  Marks_Science  Marks_Hindi
0       Sai           96             94           90
1  Giridhar          100             95           95
2     Phani           99             95           97
3    Aditya          100            100          100

In [118]:
cust = pd.merge(df_exam1, df_exam2, on='Name')
cust

Name  Marks_Science_x  Marks_Maths_x  Marks_Maths_y  Marks_Science_y  \
0  Giridhar               95             99            100               95   
1     Phani               90            100             99               95   
2       Sai               93             95             96               94   

   Marks_Hindi  
0           95  
1           97  
2           90

In [120]:
inicols = df_exam1.columns

In [121]:
fincols = cust.columns

In [126]:
inicols = list(inicols)

In [125]:
fincols = list(fincols)

In [128]:
for col in inicols:
    fincols.index('')

['Name',
 'Marks_Science_x',
 'Marks_Maths_x',
 'Marks_Maths_y',
 'Marks_Science_y',
 'Marks_Hindi']

In [131]:
df_exam2

Name  Marks_Maths  Marks_Science  Marks_Hindi
0       Sai           96             94           90
1  Giridhar          100             95           95
2     Phani           99             95           97
3    Aditya          100            100          100

In [134]:
for col in list(df_exam1.columns):
    print(df_exam2.columns.get_loc(col))

0
2
1


In [135]:
df_exam1.columns

Index(['Name', 'Marks_Science', 'Marks_Maths'], dtype='object')

In [136]:
df_exam2.columns

Index(['Name', 'Marks_Maths', 'Marks_Science', 'Marks_Hindi'], dtype='object')

In [153]:
for col in list(df_exam1.columns):
    # take the Series of resp col
    ser_1 = df_exam1[col]
    #ser_2 = df_exam2[df_exam2.columns.get_loc(col)]
    ser_2 = df_exam2[df_exam2.columns[df_exam2.columns.get_loc(col)]]
    

       Name
0  Giridhar
1     Phani
2       Sai
   Marks_Science
0             95
1             95
   Marks_Maths
0           99
1          100
2          100


In [141]:
df_exam2.columns.get_loc('Marks_Maths')

1

In [144]:
df_exam2[df_exam2.columns[1]]

0     96
1    100
2     99
3    100
Name: Marks_Maths, dtype: int64

In [150]:
ser_1

0     99
1    100
2     95
Name: Marks_Maths, dtype: int64

In [151]:
ser_2

0     96
1    100
2     99
3    100
Name: Marks_Maths, dtype: int64

In [154]:
cust

Name  Marks_Science_x  Marks_Maths_x  Marks_Maths_y  Marks_Science_y  \
0  Giridhar               95             99            100               95   
1     Phani               90            100             99               95   
2       Sai               93             95             96               94   

   Marks_Hindi  
0           95  
1           97  
2           90

In [159]:
new = pd.DataFrame(cust['Marks_Science_x'] == cust['Marks_Science_y'])
new = pd.DataFrame(merged[merged.columns[merged.columns.get_loc(col)]])

In [160]:
new

0
0   True
1  False
2  False

In [161]:
cust

Name  Marks_Science_x  Marks_Maths_x  Marks_Maths_y  Marks_Science_y  \
0  Giridhar               95             99            100               95   
1     Phani               90            100             99               95   
2       Sai               93             95             96               94   

   Marks_Hindi  
0           95  
1           97  
2           90

In [172]:
df_exam2.columns.get_loc(col)

3

In [174]:
list(cust.columns)

['Name',
 'Marks_Science_x',
 'Marks_Maths_x',
 'Marks_Maths_y',
 'Marks_Science_y',
 'Marks_Hindi']

In [177]:
list(df_exam1.columns)
    

['Name', 'Marks_Science', 'Marks_Maths']

In [209]:
res1 = 0
res2 = 0
newdf = pd.DataFrame()
for i in list(df_exam1.columns):
    print(i)
    if i+'_x' in list(cust.columns):
        res1 = list(cust.columns).index(i+'_x')
        print(res1)
    if i+'_y' in list(cust.columns):
        res2 =list(cust.columns).index(i+'_y')
        print(res2)
#     print(cust[cust.columns[res1]])
#     print(cust[cust.columns[res2]])
#     print(cust[cust.columns[res1]] == cust[cust.columns[res2]])
    
    # new df code
    ser_name = i
    ser = pd.Series(cust[cust.columns[res1]] == cust[cust.columns[res2]])
    newdf[ser_name] = ser
    

Name
Marks_Science
1
4
Marks_Maths
2
3


In [199]:
cust.columns[1]

'Marks_Science_x'

In [210]:
newdf

Name  Marks_Science  Marks_Maths
0  True           True        False
1  True          False        False
2  True          False        False

In [211]:
import os
os.getcwd()

'/Users/z003z7n/Documents/AI2019/DS_Practice/NumpyPandas2020/Refactored_Py_DS_ML_Bootcamp-master/01-Python-Crash-Course'

# Numpy

In [212]:
import numpy as np

In [214]:
# 1 d array
one_d = np.array([0])

In [216]:
type(one_d)

numpy.ndarray

In [223]:
one_d.shape

(1,)

In [224]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [225]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [226]:
# arange
arange = np.arange(1,10)

In [227]:
arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
# adding stepsize to arange
arange_step = np.arange(1,10,2)

In [230]:
arange_step.shape

(5,)

In [231]:
arange_step

array([1, 3, 5, 7, 9])

In [236]:
# zeroes
zeros = np.zeros((2,4))

In [237]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [238]:
# ones
ones = np.ones((2,4))

In [239]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [240]:
# linspace - linearly space inbetween a range and number of points.
lin = np.linspace(0,5,10)

In [242]:
lin

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [244]:
# identity
iden = np.eye(5)

In [245]:
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [247]:
# arrays of random numbers

np.random.rand(3,4)

array([[0.91921953, 0.42039085, 0.82432852, 0.86436628],
       [0.27588901, 0.19231357, 0.17817822, 0.29931975],
       [0.93068457, 0.03062889, 0.13441288, 0.40562134]])

In [249]:
np.random.rand(5)
# uniform distribution

array([0.6185165 , 0.92167147, 0.74812375, 0.50098518, 0.79537002])

In [250]:
# normal distribution
np.random.randn(2)

array([ 1.38025686, -0.90683946])

In [251]:
np.random.randn(3,4)

array([[ 0.86770117,  0.23083658, -0.43439469,  1.14113196],
       [-0.31274107,  0.47611177, -0.69368867, -1.61622123],
       [-0.87464252,  0.11380084,  0.70695871,  0.15584969]])

In [253]:
# random integers
np.random.randint(1,1000,10)

array([958, 537, 153, 900, 376, 879, 897, 362, 714,  14])

In [254]:
# useful attributes of array
arr = np.arange(25)

In [255]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [256]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [257]:
arr_rand = np.random.randint(1,100,25)

In [258]:
arr_rand

array([64, 49, 27, 77, 36, 71, 81, 38, 24, 95, 19, 49, 74, 21, 10, 60, 70,
       13, 81,  7, 77, 39, 75, 67, 47])

In [259]:
arr_rand.shape

(25,)

In [260]:
arr_rand.reshape(1,25)

array([[64, 49, 27, 77, 36, 71, 81, 38, 24, 95, 19, 49, 74, 21, 10, 60,
        70, 13, 81,  7, 77, 39, 75, 67, 47]])

In [261]:
arr_rand.shape

(25,)

In [262]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [263]:
arr.max()

24

In [264]:
arr.min()

0

In [265]:
arr.argmax()

24

In [266]:
arr_rand.max()

95

In [267]:
arr_rand.min()

7

In [268]:
arr_rand

array([64, 49, 27, 77, 36, 71, 81, 38, 24, 95, 19, 49, 74, 21, 10, 60, 70,
       13, 81,  7, 77, 39, 75, 67, 47])

In [269]:
arr_rand.argmax()

9

In [270]:
from numpy.random import randint
a  = randint(40,44)

In [271]:
a

42

In [272]:
# Numpy operations
# Array with Array operations
arr = np.arange(0,11)


In [273]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [274]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [275]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [276]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [277]:
# Array to Scalar.
arr - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [278]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [279]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [280]:
# Universal Array functions
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [281]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [283]:
arr.max()

10