In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [9]:
L = list(range(10))

In [10]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
# numpy arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
a = np.zeros(10, dtype='int')
b = np.ones(10, dtype='int')
# Arithmetic operations on a, b
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(b ^ a)
print(b ** 2)

[1 1 1 1 1 1 1 1 1 1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]


In [30]:
# arrays
c = np.zeros(10, dtype='int')

In [31]:
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
#creating a 3 row x 5 column matrix
array_3x5 = np.ones((3,5), dtype='int')

In [33]:
array_3x5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
array_5x3 = np.ones((5,3), dtype='int')

In [39]:
array_5x3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
array_3x5 * 5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [41]:
#creating a matrix with a predefined value
np.full((3,5),2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [44]:
#creating an array with a set sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
#create an array of even space between the given range of values
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [68]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
test = np.random.normal(0,1,(3,3))

In [73]:
# mean of each row (axis = 1), each column (axis = 0)
test.mean(axis=1)

array([ 0.25731449, -0.90792568, -0.1984181 ])

In [75]:
#create an identity matrix
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Important

In [90]:
#set a random seed 
# https://www.sharpsightlabs.com/blog/numpy-random-seed/
np.random.seed(1)
np.random.randint(low=1, high=20, size=10)

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17])

In [96]:
# creating a random seed
np.random.seed(0)
np.random.randint(10, size=5)

array([5, 0, 3, 3, 7])

In [97]:
# creating again with the seed 0
np.random.seed(0)
np.random.randint(10, size = 5)

array([5, 0, 3, 3, 7])

In [98]:
# new seed 1
np.random.seed(1)
np.random.randint(10, size=5)

array([5, 8, 9, 5, 0])

In [100]:
# testing seed 1 again
np.random.seed(0)
np.random.randint(10, size=5)

array([5, 0, 3, 3, 7])

In [101]:
np.random.seed(1)
np.random.randint(20, size=5)

array([ 5, 11, 12,  8,  9])

In [103]:
x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension

In [104]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


In [105]:
x3

array([[[6, 9, 9, 7, 6],
        [9, 1, 0, 1, 8],
        [8, 3, 9, 8, 7],
        [3, 6, 5, 1, 9]],

       [[3, 4, 8, 1, 4],
        [0, 3, 9, 2, 0],
        [4, 9, 2, 7, 7],
        [9, 8, 6, 9, 3]],

       [[7, 7, 4, 5, 9],
        [3, 6, 8, 0, 2],
        [7, 7, 9, 7, 3],
        [0, 8, 7, 7, 1]]])

In [106]:
# Indexing
ind = np.array([2,3,4,5])

In [109]:
print(ind[0], ind[1], ind[2], ind[3], ind[-1])

2 3 4 5 5


In [113]:
mul_ind = np.random.randint(10,size=(3,4))
mul_ind

array([[4, 4, 7, 7],
       [4, 9, 0, 2],
       [0, 7, 1, 7]])

In [115]:
print(mul_ind[2,3])

7


# Array Slicing

In [116]:
x = np.arange(10)

In [117]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
x[0:5]

array([0, 1, 2, 3, 4])

In [119]:
x[-1]

9

In [125]:
#return elements at even place
x[::2]

array([0, 2, 4, 6, 8])

In [130]:
#return elements from first position step by two
x[1::2]

array([1, 3, 5, 7, 9])

In [128]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Array Concatenation

In [134]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([20,21,22])

In [138]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6, 20, 21, 22])

In [152]:
# two dimensional arrays
td = np.array([[1,2,3],[4,5,6]])
td2 = np.array([1,2,3,4])
td.shape

(2, 3)

In [146]:
new_td = np.concatenate([td,td])

In [147]:
new_td

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [148]:
new_td.shape

(4, 3)

In [149]:
#Using its axis parameter, you can define row-wise or column-wise matrix
td

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
td_rowwise = np.concatenate([td,td],axis=1)

In [151]:
td_rowwise

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [153]:
# just to see the error
np.concatenate([td,td2])

ValueError: all the input arrays must have same number of dimensions

In [156]:
# np.vstack, np.hstack will help us to concatenate 2D, 3D.
dim2 = np.array([1,2,3])
dim3 = np.array([[4,5,6],[7,8,9]])
vstack = np.vstack([dim2, dim3])
vstack

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
#np.hstack
dim2 = np.array([[7],[10]])
dim3 = np.array([[4,5,6],[7,8,9]])
hstack = np.hstack([dim2, dim3])
hstack

array([[ 7,  4,  5,  6],
       [10,  7,  8,  9]])

# Also, we can split the arrays based on pre-defined positions. Let's see how!

In [159]:
x = np.arange(10)

In [161]:
x1, x2, x3 = np.split(x,[3,6])

In [162]:
x1

array([0, 1, 2])

In [163]:
x2

array([3, 4, 5])

In [164]:
x3

array([6, 7, 8, 9])

In [165]:
grid = np.arange(16).reshape(4,4)

In [166]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [167]:
upper, lower = np.vsplit(grid,[2])

In [168]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [169]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [170]:
grid2 = np.arange(16).reshape(4,4)

In [171]:
grid2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [172]:
left, right = np.hsplit(grid2,[2])

In [173]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [174]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])