In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [9]:
L = list(range(10))

In [10]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
# numpy arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
a = np.zeros(10, dtype='int')
b = np.ones(10, dtype='int')
# Arithmetic operations on a, b
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(b ^ a)
print(b ** 2)

[1 1 1 1 1 1 1 1 1 1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]


In [30]:
# arrays
c = np.zeros(10, dtype='int')

In [31]:
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
#creating a 3 row x 5 column matrix
array_3x5 = np.ones((3,5), dtype='int')

In [33]:
array_3x5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
array_5x3 = np.ones((5,3), dtype='int')

In [39]:
array_5x3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
array_3x5 * 5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [41]:
#creating a matrix with a predefined value
np.full((3,5),2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [44]:
#creating an array with a set sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
#create an array of even space between the given range of values
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [68]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
test = np.random.normal(0,1,(3,3))

In [73]:
# mean of each row (axis = 1), each column (axis = 0)
test.mean(axis=1)

array([ 0.25731449, -0.90792568, -0.1984181 ])

In [75]:
#create an identity matrix
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Important

In [90]:
#set a random seed 
# https://www.sharpsightlabs.com/blog/numpy-random-seed/
np.random.seed(1)
np.random.randint(low=1, high=20, size=10)

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17])

In [96]:
# creating a random seed
np.random.seed(0)
np.random.randint(10, size=5)

array([5, 0, 3, 3, 7])

In [97]:
# creating again with the seed 0
np.random.seed(0)
np.random.randint(10, size = 5)

array([5, 0, 3, 3, 7])

In [98]:
# new seed 1
np.random.seed(1)
np.random.randint(10, size=5)

array([5, 8, 9, 5, 0])

In [100]:
# testing seed 1 again
np.random.seed(0)
np.random.randint(10, size=5)

array([5, 0, 3, 3, 7])

In [101]:
np.random.seed(1)
np.random.randint(20, size=5)

array([ 5, 11, 12,  8,  9])

In [103]:
x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension

In [104]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


In [105]:
x3

array([[[6, 9, 9, 7, 6],
        [9, 1, 0, 1, 8],
        [8, 3, 9, 8, 7],
        [3, 6, 5, 1, 9]],

       [[3, 4, 8, 1, 4],
        [0, 3, 9, 2, 0],
        [4, 9, 2, 7, 7],
        [9, 8, 6, 9, 3]],

       [[7, 7, 4, 5, 9],
        [3, 6, 8, 0, 2],
        [7, 7, 9, 7, 3],
        [0, 8, 7, 7, 1]]])

In [106]:
# Indexing
ind = np.array([2,3,4,5])

In [109]:
print(ind[0], ind[1], ind[2], ind[3], ind[-1])

2 3 4 5 5


In [113]:
mul_ind = np.random.randint(10,size=(3,4))
mul_ind

array([[4, 4, 7, 7],
       [4, 9, 0, 2],
       [0, 7, 1, 7]])

In [115]:
print(mul_ind[2,3])

7
